server:
  port: 18083

spring:
  application:
    name: customer-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: qcb
    password: 123456

  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.alibaba.nacos.client.naming: WARN


